# Aliases for using bare git as dotfiles storage
alias dot="git --git-dir=$HOME/.dotfiles --work-tree ~"
alias dst="dot status"
alias da="dot add"
alias daa="dot add -u"
alias drm="dot rm"
alias dc="dot commit"
alias dcm="dot commit -m"
alias dp="dot push"
alias dpr="dot pull --rebase"
alias dpra="dot pull --rebase --auto-stash"
